[package]
name = "text-processing"
version = "0.1.0"
authors = ["chathura.colombage <dcdewaka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
twoway = "0.2.1"