[package]
name = "parallel-processing"
version = "0.1.0"
authors = ["Chathura Colombage <dcdewaka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.3.0"
